version: '3.8'

services:
  # 1. Jenkins CI Sunucusu
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8081:8080"        # Jenkins Web Arayüzü
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # KRİTİK: Jenkins'in Docker komutlarını çalıştırması için
    container_name: jenkins-server
    networks:
      - ci-cd-network

  # 2. Uygulama Servisi (Jenkins'in kullanması için burada tanımlı OLMALIDIR)
  # Jenkins, 'docker-compose up kutuphane-app' dediğinde bu tanımı kullanacaktır.
  kutuphane-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kutuphane-app-server
    ports:
      - "8081:8080" # Host'taki 8081'i kullanacağız
    networks:
      - ci-cd-network
    # Deployment Jenkins'e ait olduğu için 'restart: unless-stopped' gibi ayarlar burada opsiyoneldir.


volumes:
  jenkins_home:

networks:
  ci-cd-network:
    driver: bridge